DB_USER = "root"
DB_PASSWORD = "ssolitim0925"
DB_HOST = "13.209.121.22"
DB_NAME = "ssolitim"

SQLALCHEMY_DATABASE_URI = f"mysql+pymysql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}/{DB_NAME}"
SQLALCHEMY_TRACK_MODIFICATIONS = False